name: AndroidBuild
# Controls when the workflow will run
on:
  workflow_call:

jobs:
  build:
    runs-on : ubuntu-latest
    steps:

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"