name: AndroidBuild
on:
  pull_request:
    branches : [ master ]
  push :
    branches : [ master ]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout
        uses: actions/checkout@v4.1.1
      - run: echo "The ${{ github.repository }} repository has been cloned."

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: echo "The workflow is now ready to test your code."

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle command - lintDebug
        run: ./gradlew lintDebug