name: Job Test CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Test CI
    runs-on: ubuntu-latest

    steps:

      - name: Generate App Version Name
        run: echo "VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')" >> $GITHUB_ENV
      - run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - run: echo "${{ env.VERSION_NAME  }}"
      - run: echo "${{ secrets.SIGNING_KEY_ALIAS  }}"
