name: Job Test CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Test CI
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set Version Name
        run: |
          VERSION_NAME=$(git describe --tags | sed 's/\(.*\)-/\1./' | sed 's/\(.*\)-/\1+/')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - run: echo "${{ env.VERSION_NAME  }}"
      - run: echo "${{ secrets.SIGNING_KEY_ALIAS  }}"
