
name: Create Build - Manual workflow

on:
  workflow_dispatch:

jobs:

  app_release:
    name: Create Build

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Get branch name
        id: branch_name
        run: echo "name=$(echo $GITHUB_REF | sed -n 's/refs\/heads\///p')" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Building Debug APK
        run: ./gradlew build

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}

#      - name: Upload APK Debug - ${{ env.repository_name }}
#        uses: actions/upload-artifact@v3.1.3
#        with:
#          name: ${{ steps.branch_name.outputs.name }} - APK(s) debug generated
#          path: app/build/outputs/apk/debug/app-debug.apk

#      - name: Current date
#        id: current_date
#        run: echo "name=$(date +'%d_%m_%_Y__%H_%M_%S')" >> $GITHUB_OUTPUT
#
#      - run: echo "Current date ${{ steps.current_date.outputs.name }}"
#
#      - name: Get branch name
#        id: branch_name
#        run: echo "name=$(echo $GITHUB_REF | sed -n 's/refs\/heads\///p')" >> $GITHUB_OUTPUT
#
#
#      - run: echo "Branch name  ${{ steps.branch_name.outputs.name }}"
#
#
#      - name: Set build name
#        id: set_build_name
#        run: |
#          build_name="${{ steps.branch_name.outputs.name }}-${{ steps.current_date.outputs.name }}"
#          echo "::set-output name=build_name::$build_name"
#
#
#      - name: Display build name
#        run: echo "${{ steps.set_build_name.outputs.build_name }}"
#
#      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"




#      - name: Get branch name
#        id: branch_name
#        run: echo "::set-output name=name::$(echo $GITHUB_REF | sed -n 's/refs\/heads\///p')"
#

#      - name: Store LXD version
#        id: set_lxd_version
#        run: echo "build_name=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
#      - run: echo "Test ${{ steps.set_lxd_version.outputs.build_name }}"

#      - run: echo "${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated"

#      - name: Get current date
#        id: date
#        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
#      - name: Test with environment variables
#        run: echo $TAG_NAME - $RELEASE_NAME
#        env:
#          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
#          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
#      - name: Test with input
#        uses: actions/hello-world-docker-action@master
#        with:
#          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}











#      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
#
#      - run: echo "${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated"
#
#      - name: Get branch name
#        id: branch_name
#        run: echo "::set-output name=name::$(echo $GITHUB_REF | sed -n 's/refs\/heads\///p')"

#      - name: Get current date
#        id: current_date
#      - run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
#
#      - name: Set build name
#        id: set_build_name
#        run: |
#          build_name="${{ steps.branch_name.outputs.name }}-${{ steps.current_date.outputs.date }}"
#          echo "::set-output name=build_name::$build_name"
#
#      - name: Display build name
#      - run: echo "${{ steps.set_build_name.outputs.build_name }}"